In [1]:
import pandas as pd

In [2]:
import pandas as pd

# Read the Excel file
arrival_delta = pd.read_csv("/Users/vaibhavkrishnajoshi/Documents/iml_24/filtered_Arrivals_delta.csv")





arrival_delta.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,9E,1/1/23,5190.0,N325PQ,JFK,22:41,22:13,91.0,68.0,-28.0,22:09,4.0,0.0,0.0,0.0,0.0,0.0
1,9E,1/2/22,5531.0,N678CA,JFK,14:12,17:12,77.0,84.0,180.0,17:01,11.0,173.0,0.0,7.0,0.0,0.0
2,9E,1/2/23,5190.0,N195PQ,JFK,22:41,22:46,91.0,77.0,5.0,22:42,4.0,0.0,0.0,0.0,0.0,0.0
3,9E,1/3/22,5531.0,N602LR,JFK,14:12,14:24,77.0,81.0,12.0,14:20,4.0,0.0,0.0,0.0,0.0,0.0
4,9E,1/3/23,5190.0,N303PQ,JFK,22:41,22:23,91.0,78.0,-18.0,22:19,4.0,0.0,0.0,0.0,0.0,0.0

In [3]:
arrival_mq = pd.read_csv("/Users/vaibhavkrishnajoshi/Documents/iml_24/filtered_Arrivals_mq.csv")
arrival_mq.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,MQ,1/1/22,4316.0,N900AE,ORD,18:15,0:00,107.0,0.0,0.0,0:00,0.0,0.0,0.0,0.0,0.0,0.0
1,MQ,1/1/23,3392.0,N283NN,ORD,21:16,21:08,111.0,104.0,-8.0,21:02,6.0,0.0,0.0,0.0,0.0,0.0
2,MQ,1/1/23,3518.0,N213NN,ORD,16:02,15:37,117.0,96.0,-25.0,15:33,4.0,0.0,0.0,0.0,0.0,0.0
3,MQ,1/2/22,4134.0,N900AE,ORD,13:16,13:47,111.0,146.0,31.0,13:43,4.0,0.0,0.0,31.0,0.0,0.0
4,MQ,1/2/22,4253.0,N238NN,ORD,20:12,20:47,107.0,116.0,35.0,20:40,7.0,0.0,26.0,9.0,0.0,0.0

In [4]:
arrival_jb = pd.read_csv("/Users/vaibhavkrishnajoshi/Documents/iml_24/filtered_Arrivals_jb.csv")
arrival_jb.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,B6,1/1/22,656.0,N375JB,MCO,15:56,16:18,163.0,160.0,22.0,16:14,4.0,22.0,0.0,0.0,0.0,0.0
1,B6,1/1/22,2516.0,N346JB,JFK,22:59,23:35,74.0,74.0,36.0,23:30,5.0,36.0,0.0,0.0,0.0,0.0
2,B6,1/1/23,116.0,N355JB,JFK,14:48,15:11,73.0,63.0,23.0,15:08,3.0,10.0,0.0,0.0,0.0,13.0
3,B6,1/1/23,656.0,N583JB,MCO,18:28,19:05,163.0,192.0,37.0,18:50,15.0,3.0,0.0,29.0,0.0,5.0
4,B6,1/1/23,2516.0,N216JB,JFK,23:41,23:25,71.0,61.0,-16.0,23:20,5.0,0.0,0.0,0.0,0.0,0.0

In [5]:
arrival_sw = pd.read_csv("/Users/vaibhavkrishnajoshi/Documents/iml_24/filtered_Arrivals_sw.csv")
arrival_sw.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,WN,1/1/22,1596.0,N730SW,MCO,13:20,12:54,170.0,142.0,-26.0,12:51,3.0,0.0,0.0,0.0,0.0,0.0
1,WN,1/7/23,2695.0,N8318F,MCO,13:45,13:46,160.0,161.0,1.0,13:43,3.0,0.0,0.0,0.0,0.0,0.0
2,WN,1/14/23,2695.0,N8555Z,MCO,13:45,14:02,160.0,180.0,17.0,13:59,3.0,0.0,0.0,17.0,0.0,0.0
3,WN,1/21/23,2695.0,N500WR,MCO,13:45,13:37,160.0,156.0,-8.0,13:35,2.0,0.0,0.0,0.0,0.0,0.0
4,WN,1/22/22,3479.0,N8690A,MCO,14:45,14:35,165.0,147.0,-10.0,14:32,3.0,0.0,0.0,0.0,0.0,0.0

In [6]:
arrival_united = pd.read_csv("/Users/vaibhavkrishnajoshi/Documents/iml_24/filtered_Arrivals_uni.csv")
arrival_united.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,UA,1/1/23,2645.0,N23721,ORD,23:57,23:47,107.0,100.0,-10.0,23:41,6.0,0.0,0.0,0.0,0.0,0.0
1,UA,1/2/23,1998.0,N802UA,ORD,21:07,20:46,113.0,89.0,-21.0,20:43,3.0,0.0,0.0,0.0,0.0,0.0
2,UA,1/3/23,1998.0,N854UA,ORD,21:07,21:04,113.0,111.0,-3.0,20:58,6.0,0.0,0.0,0.0,0.0,0.0
3,UA,1/4/23,1998.0,N893UA,ORD,21:17,21:31,113.0,110.0,14.0,21:26,5.0,0.0,0.0,0.0,0.0,0.0
4,UA,1/5/23,1998.0,N853UA,ORD,21:17,21:17,113.0,112.0,0.0,21:11,6.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# Concatenate arrival data for all carriers into a single DataFrame
arrival_data_combined = pd.concat([arrival_delta, arrival_mq, arrival_jb, arrival_sw, arrival_united], ignore_index=True)
arrival_data_combined.head(20)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,9E,1/1/23,5190.0,N325PQ,JFK,22:41,22:13,91.0,68.0,-28.0,22:09,4.0,0.0,0.0,0.0,0.0,0.0
1,9E,1/2/22,5531.0,N678CA,JFK,14:12,17:12,77.0,84.0,180.0,17:01,11.0,173.0,0.0,7.0,0.0,0.0
2,9E,1/2/23,5190.0,N195PQ,JFK,22:41,22:46,91.0,77.0,5.0,22:42,4.0,0.0,0.0,0.0,0.0,0.0
3,9E,1/3/22,5531.0,N602LR,JFK,14:12,14:24,77.0,81.0,12.0,14:20,4.0,0.0,0.0,0.0,0.0,0.0
4,9E,1/3/23,5190.0,N303PQ,JFK,22:41,22:23,91.0,78.0,-18.0,22:19,4.0,0.0,0.0,0.0,0.0,0.0
5,9E,1/4/22,5531.0,N279PQ,JFK,14:12,13:52,77.0,66.0,-20.0,13:49,3.0,0.0,0.0,0.0,0.0,0.0
6,9E,1/4/23,5190.0,N606LR,JFK,22:41,22:29,91.0,84.0,-12.0,22:25,4.0,0.0,0.0,0.0,0.0,0.0
7,9E,1/5/22,5446.0,N906XJ,JFK,13:45,13:29,75.0,67.0,-16.0,13:24,5.0,0.0,0.0,0.0,0.0,0.0
8,9E,1/5/23,5190.0,N183GJ,JFK,22:41,22:21,91.0,78.0,-20.0,22:17,4.0,0.0,0.0,0.0,0.0,0.0
9,9E,1/6/22,5446.0,N906XJ,JFK,13:45,13:28,75.0,63.0,-17.0,13:24,4.0,0.0,0.0,0.0,0.0,0.0
10,9E,1/6/23,5190.0,N195PQ,JFK,22:41,22:21,91.0,76.0,-20.0,22:16,5.0,0.0,0.0,0.0,0.0,0.0
11,9E,1/7/22,5446.0,N182GJ,JFK,13:45,15:00,75.0,65.0,75.0,14:55,5.0,0.0,22.0,0.0,0.0,53.0
12,9E,1/7/23,5190.0,N301PQ,JFK,22:41,22:19,91.0,72.0,-22.0,22:14,5.0,0.0,0.0,0.0,0.0,0.0
13,9E,1/8/22,5446.0,N166PQ,JFK,13:45,13:28,75.0,66.0,-17.0,13:23,5.0,0.0,0.0,0.0,0.0,0.0
14,9E,1/8/23,5090.0,N300PQ,JFK,23:58,23:25,88.0,63.0,-33.0,23:22,3.0,0.0,0.0,0.0,0.0,0.0
15,9E,1/8/23,5114.0,N335PQ,JFK,17:48,17:39,88.0,64.0,-9.0,17:35,4.0,0.0,0.0,0.0,0.0,0.0
16,9E,1/8/23,5202.0,N304PQ,JFK,11:14,10:53,84.0,64.0,-21.0,10:48,5.0,0.0,0.0,0.0,0.0,0.0
17,9E,1/9/22,5446.0,N153PQ,JFK,13:45,13:50,75.0,81.0,5.0,13:45,5.0,0.0,0.0,0.0,0.0,0.0
18,9E,1/9/23,5009.0,N131EV,JFK,23:54,23:36,84.0,71.0,-18.0,23:32,4.0,0.0,0.0,0.0,0.0,0.0
19,9E,1/9/23,5224.0,N936XJ,JFK,17:55,18:22,85.0,83.0,27.0,18:17,5.0,26.0,0.0,0.0,0.0,1.0

In [8]:
len(arrival_data_combined)

5623

In [9]:
print(len(arrival_delta))
print(len(arrival_mq))
print(len(arrival_jb))
print(len(arrival_sw))
print(len(arrival_united))

1747
1001
1835
179
861

In [10]:
departure_aa = pd.read_csv("/Users/vaibhavkrishnajoshi/Documents/iml_24/filtered_Departure_ord_mq.csv")
departure_aa.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,MQ,1/1/22,4316.0,N900AE,SYR,15:28,0:00,107.0,0.0,0.0,0:00,0.0,0.0,0.0,0.0,0.0,0.0
1,MQ,1/1/23,3392.0,N283NN,SYR,18:25,18:24,111.0,104.0,-1.0,18:45,21.0,0.0,0.0,0.0,0.0,0.0
2,MQ,1/1/23,3518.0,N213NN,SYR,13:05,13:01,117.0,96.0,-4.0,13:16,15.0,0.0,0.0,0.0,0.0,0.0
3,MQ,1/2/22,4134.0,N900AE,SYR,10:25,10:21,111.0,146.0,-4.0,11:24,63.0,0.0,0.0,31.0,0.0,0.0
4,MQ,1/2/22,4253.0,N238NN,SYR,17:25,17:51,107.0,116.0,26.0,18:22,31.0,0.0,26.0,9.0,0.0,0.0

In [11]:
departure_jfk_jb = pd.read_csv("/Users/vaibhavkrishnajoshi/Documents/iml_24/filtered_Departure_jfk_jb.csv")
departure_jfk_jb.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,B6,1/1/22,2516.0,N346JB,SYR,21:45,22:21,74.0,74.0,36.0,22:43,22.0,36.0,0.0,0.0,0.0,0.0
1,B6,1/1/23,116.0,N355JB,SYR,13:35,14:08,73.0,63.0,33.0,14:22,14.0,10.0,0.0,0.0,0.0,13.0
2,B6,1/1/23,2516.0,N216JB,SYR,22:30,22:24,71.0,61.0,-6.0,22:36,12.0,0.0,0.0,0.0,0.0,0.0
3,B6,1/2/22,116.0,N294JB,SYR,8:29,8:28,81.0,70.0,-1.0,8:44,16.0,0.0,0.0,0.0,0.0,0.0
4,B6,1/2/22,2516.0,N316JB,SYR,21:45,0:00,74.0,0.0,0.0,0:00,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
departure_jfk_end = pd.read_csv("/Users/vaibhavkrishnajoshi/Documents/iml_24/filtered_Departure_jfk_end.csv")
departure_jfk_end.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,9E,1/1/23,5190.0,N325PQ,SYR,21:10,21:05,91.0,68.0,-5.0,21:23,18.0,0.0,0.0,0.0,0.0,0.0
1,9E,1/2/22,5531.0,N678CA,SYR,12:55,15:48,77.0,84.0,173.0,16:08,20.0,173.0,0.0,7.0,0.0,0.0
2,9E,1/2/23,5190.0,N195PQ,SYR,21:10,21:29,91.0,77.0,19.0,21:54,25.0,0.0,0.0,0.0,0.0,0.0
3,9E,1/3/22,5531.0,N602LR,SYR,12:55,13:03,77.0,81.0,8.0,13:34,31.0,0.0,0.0,0.0,0.0,0.0
4,9E,1/3/23,5190.0,N303PQ,SYR,21:10,21:05,91.0,78.0,-5.0,21:35,30.0,0.0,0.0,0.0,0.0,0.0

In [13]:
departure_mco_jb = pd.read_csv("/Users/vaibhavkrishnajoshi/Documents/iml_24/filtered_Departure_mco_jb.csv")
departure_mco_jb.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,B6,1/1/22,656.0,N375JB,SYR,13:13,13:38,163.0,160.0,25.0,13:56,18.0,22.0,0.0,0.0,0.0,0.0
1,B6,1/1/23,656.0,N583JB,SYR,15:45,15:53,163.0,192.0,8.0,16:17,24.0,3.0,0.0,29.0,0.0,5.0
2,B6,1/2/22,656.0,N279JB,SYR,13:13,14:29,163.0,151.0,76.0,14:44,15.0,34.0,0.0,0.0,0.0,30.0
3,B6,1/2/23,656.0,N639JB,SYR,15:45,16:43,163.0,173.0,58.0,17:03,20.0,11.0,0.0,10.0,0.0,47.0
4,B6,1/3/22,656.0,N193JB,SYR,13:13,13:00,163.0,166.0,-13.0,13:25,25.0,0.0,0.0,0.0,0.0,0.0

In [14]:
departure_mco_sw = pd.read_csv("/Users/vaibhavkrishnajoshi/Documents/iml_24/filtered_Departure_mco_sw.csv")
departure_mco_sw.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,WN,1/1/22,1596.0,N730SW,SYR,10:30,10:32,170.0,142.0,2.0,10:38,6.0,0.0,0.0,0.0,0.0,0.0
1,WN,1/7/23,2695.0,N8318F,SYR,11:05,11:05,160.0,161.0,0.0,11:17,12.0,0.0,0.0,0.0,0.0,0.0
2,WN,1/14/23,2695.0,N8555Z,SYR,11:05,11:02,160.0,180.0,-3.0,11:29,27.0,0.0,0.0,17.0,0.0,0.0
3,WN,1/21/23,2695.0,N500WR,SYR,11:05,11:01,160.0,156.0,-4.0,11:15,14.0,0.0,0.0,0.0,0.0,0.0
4,WN,1/22/22,3479.0,N8690A,SYR,12:00,12:08,165.0,147.0,8.0,12:25,17.0,0.0,0.0,0.0,0.0,0.0

In [15]:
departure_ord_uni = pd.read_csv("/Users/vaibhavkrishnajoshi/Documents/iml_24/filtered_Departure_ord_uni.csv")
departure_ord_uni.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,UA,1/1/23,2645.0,N23721,SYR,21:10,21:07,107.0,100.0,-3.0,21:27,20.0,0.0,0.0,0.0,0.0,0.0
1,UA,1/2/23,1998.0,N802UA,SYR,18:14,18:17,113.0,89.0,3.0,18:34,17.0,0.0,0.0,0.0,0.0,0.0
2,UA,1/3/23,1998.0,N854UA,SYR,18:14,18:13,113.0,111.0,-1.0,18:44,31.0,0.0,0.0,0.0,0.0,0.0
3,UA,1/4/23,1998.0,N893UA,SYR,18:24,18:41,113.0,110.0,17.0,19:14,33.0,0.0,0.0,0.0,0.0,0.0
4,UA,1/5/23,1998.0,N853UA,SYR,18:24,18:25,113.0,112.0,1.0,18:48,23.0,0.0,0.0,0.0,0.0,0.0

In [16]:
print(len(departure_aa))
print(len(departure_jfk_jb))
print(len(departure_mco_jb))
print(len(departure_mco_sw))
print(len(departure_ord_uni))
print(len(departure_jfk_end))

1001
1234
601
179
861
1747

In [17]:
departure_data_combined = pd.concat([departure_aa, departure_jfk_jb, departure_jfk_end, departure_mco_jb, departure_mco_sw, departure_ord_uni], ignore_index=True)
departure_data_combined.head(20)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,MQ,1/1/22,4316.0,N900AE,SYR,15:28,0:00,107.0,0.0,0.0,0:00,0.0,0.0,0.0,0.0,0.0,0.0
1,MQ,1/1/23,3392.0,N283NN,SYR,18:25,18:24,111.0,104.0,-1.0,18:45,21.0,0.0,0.0,0.0,0.0,0.0
2,MQ,1/1/23,3518.0,N213NN,SYR,13:05,13:01,117.0,96.0,-4.0,13:16,15.0,0.0,0.0,0.0,0.0,0.0
3,MQ,1/2/22,4134.0,N900AE,SYR,10:25,10:21,111.0,146.0,-4.0,11:24,63.0,0.0,0.0,31.0,0.0,0.0
4,MQ,1/2/22,4253.0,N238NN,SYR,17:25,17:51,107.0,116.0,26.0,18:22,31.0,0.0,26.0,9.0,0.0,0.0
5,MQ,1/2/22,4316.0,N922AE,SYR,15:28,0:00,107.0,0.0,0.0,0:00,0.0,0.0,0.0,0.0,0.0,0.0
6,MQ,1/2/23,3392.0,N248NN,SYR,17:33,17:30,106.0,102.0,-3.0,17:52,22.0,0.0,0.0,0.0,0.0,0.0
7,MQ,1/2/23,3518.0,N263NN,SYR,13:05,13:04,117.0,112.0,-1.0,13:35,31.0,0.0,0.0,0.0,0.0,0.0
8,MQ,1/3/22,4134.0,N606AE,SYR,10:25,10:23,111.0,94.0,-2.0,10:34,11.0,0.0,0.0,0.0,0.0,0.0
9,MQ,1/3/22,4253.0,N200NN,SYR,17:25,17:35,107.0,109.0,10.0,18:04,29.0,0.0,0.0,0.0,0.0,0.0
10,MQ,1/3/22,4316.0,N900AE,SYR,15:28,15:29,107.0,104.0,1.0,15:45,16.0,0.0,0.0,0.0,0.0,0.0
11,MQ,1/3/23,3392.0,N276NN,SYR,17:33,18:04,106.0,113.0,31.0,18:39,35.0,19.0,0.0,7.0,0.0,12.0
12,MQ,1/3/23,3518.0,N244NN,SYR,13:05,13:03,117.0,106.0,-2.0,13:33,30.0,0.0,0.0,0.0,0.0,0.0
13,MQ,1/4/23,3392.0,N237NN,SYR,17:33,17:29,106.0,120.0,-4.0,18:11,42.0,0.0,0.0,0.0,0.0,0.0
14,MQ,1/4/23,3518.0,N256NN,SYR,13:05,13:09,117.0,117.0,4.0,13:45,36.0,0.0,0.0,0.0,0.0,0.0
15,MQ,1/5/23,3518.0,N274NN,SYR,13:05,13:05,117.0,139.0,0.0,13:57,52.0,0.0,0.0,22.0,0.0,0.0
16,MQ,1/6/22,4134.0,N675AE,SYR,8:05,8:50,111.0,92.0,45.0,9:02,12.0,26.0,0.0,0.0,0.0,0.0
17,MQ,1/6/23,3518.0,N254NN,SYR,13:05,13:17,117.0,165.0,12.0,14:41,84.0,4.0,0.0,48.0,0.0,8.0
18,MQ,1/7/22,4134.0,N696AE,SYR,8:05,8:03,111.0,121.0,-2.0,8:13,10.0,0.0,0.0,0.0,0.0,0.0
19,MQ,1/7/23,3518.0,N760MQ,SYR,13:57,13:52,105.0,105.0,-5.0,14:06,14.0,0.0,0.0,0.0,0.0,0.0

In [18]:
len(departure_data_combined)

5623

In [19]:
arrival_data_combined.head(20)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
0,9E,1/1/23,5190.0,N325PQ,JFK,22:41,22:13,91.0,68.0,-28.0,22:09,4.0,0.0,0.0,0.0,0.0,0.0
1,9E,1/2/22,5531.0,N678CA,JFK,14:12,17:12,77.0,84.0,180.0,17:01,11.0,173.0,0.0,7.0,0.0,0.0
2,9E,1/2/23,5190.0,N195PQ,JFK,22:41,22:46,91.0,77.0,5.0,22:42,4.0,0.0,0.0,0.0,0.0,0.0
3,9E,1/3/22,5531.0,N602LR,JFK,14:12,14:24,77.0,81.0,12.0,14:20,4.0,0.0,0.0,0.0,0.0,0.0
4,9E,1/3/23,5190.0,N303PQ,JFK,22:41,22:23,91.0,78.0,-18.0,22:19,4.0,0.0,0.0,0.0,0.0,0.0
5,9E,1/4/22,5531.0,N279PQ,JFK,14:12,13:52,77.0,66.0,-20.0,13:49,3.0,0.0,0.0,0.0,0.0,0.0
6,9E,1/4/23,5190.0,N606LR,JFK,22:41,22:29,91.0,84.0,-12.0,22:25,4.0,0.0,0.0,0.0,0.0,0.0
7,9E,1/5/22,5446.0,N906XJ,JFK,13:45,13:29,75.0,67.0,-16.0,13:24,5.0,0.0,0.0,0.0,0.0,0.0
8,9E,1/5/23,5190.0,N183GJ,JFK,22:41,22:21,91.0,78.0,-20.0,22:17,4.0,0.0,0.0,0.0,0.0,0.0
9,9E,1/6/22,5446.0,N906XJ,JFK,13:45,13:28,75.0,63.0,-17.0,13:24,4.0,0.0,0.0,0.0,0.0,0.0
10,9E,1/6/23,5190.0,N195PQ,JFK,22:41,22:21,91.0,76.0,-20.0,22:16,5.0,0.0,0.0,0.0,0.0,0.0
11,9E,1/7/22,5446.0,N182GJ,JFK,13:45,15:00,75.0,65.0,75.0,14:55,5.0,0.0,22.0,0.0,0.0,53.0
12,9E,1/7/23,5190.0,N301PQ,JFK,22:41,22:19,91.0,72.0,-22.0,22:14,5.0,0.0,0.0,0.0,0.0,0.0
13,9E,1/8/22,5446.0,N166PQ,JFK,13:45,13:28,75.0,66.0,-17.0,13:23,5.0,0.0,0.0,0.0,0.0,0.0
14,9E,1/8/23,5090.0,N300PQ,JFK,23:58,23:25,88.0,63.0,-33.0,23:22,3.0,0.0,0.0,0.0,0.0,0.0
15,9E,1/8/23,5114.0,N335PQ,JFK,17:48,17:39,88.0,64.0,-9.0,17:35,4.0,0.0,0.0,0.0,0.0,0.0
16,9E,1/8/23,5202.0,N304PQ,JFK,11:14,10:53,84.0,64.0,-21.0,10:48,5.0,0.0,0.0,0.0,0.0,0.0
17,9E,1/9/22,5446.0,N153PQ,JFK,13:45,13:50,75.0,81.0,5.0,13:45,5.0,0.0,0.0,0.0,0.0,0.0
18,9E,1/9/23,5009.0,N131EV,JFK,23:54,23:36,84.0,71.0,-18.0,23:32,4.0,0.0,0.0,0.0,0.0,0.0
19,9E,1/9/23,5224.0,N936XJ,JFK,17:55,18:22,85.0,83.0,27.0,18:17,5.0,26.0,0.0,0.0,0.0,1.0

In [20]:
arrival_data_combined['Date (MM/DD/YYYY)'] = pd.to_datetime(arrival_data_combined['Date (MM/DD/YYYY)'], format='%m/%d/%y')
departure_data_combined['Date (MM/DD/YYYY)'] = pd.to_datetime(departure_data_combined['Date (MM/DD/YYYY)'], format='%m/%d/%y')

In [21]:
len(arrival_data_combined.columns)

17

In [22]:
merged_data = pd.merge(arrival_data_combined, departure_data_combined, on=['Carrier Code', 'Date (MM/DD/YYYY)', 'Flight Number', 'Tail Number'], how='left')
merged_data.head(20)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),...,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes)_y,Delay Weather (Minutes)_y,Delay National Aviation System (Minutes)_y,Delay Security (Minutes)_y,Delay Late Aircraft Arrival (Minutes)_y
0,9E,2023-01-01,5190.0,N325PQ,JFK,22:41,22:13,91.0,68.0,-28.0,...,91.0,68.0,-5.0,21:23,18.0,0.0,0.0,0.0,0.0,0.0
1,9E,2022-01-02,5531.0,N678CA,JFK,14:12,17:12,77.0,84.0,180.0,...,77.0,84.0,173.0,16:08,20.0,173.0,0.0,7.0,0.0,0.0
2,9E,2023-01-02,5190.0,N195PQ,JFK,22:41,22:46,91.0,77.0,5.0,...,91.0,77.0,19.0,21:54,25.0,0.0,0.0,0.0,0.0,0.0
3,9E,2022-01-03,5531.0,N602LR,JFK,14:12,14:24,77.0,81.0,12.0,...,77.0,81.0,8.0,13:34,31.0,0.0,0.0,0.0,0.0,0.0
4,9E,2023-01-03,5190.0,N303PQ,JFK,22:41,22:23,91.0,78.0,-18.0,...,91.0,78.0,-5.0,21:35,30.0,0.0,0.0,0.0,0.0,0.0
5,9E,2022-01-04,5531.0,N279PQ,JFK,14:12,13:52,77.0,66.0,-20.0,...,77.0,66.0,-9.0,13:00,14.0,0.0,0.0,0.0,0.0,0.0
6,9E,2023-01-04,5190.0,N606LR,JFK,22:41,22:29,91.0,84.0,-12.0,...,91.0,84.0,-5.0,21:40,35.0,0.0,0.0,0.0,0.0,0.0
7,9E,2022-01-05,5446.0,N906XJ,JFK,13:45,13:29,75.0,67.0,-16.0,...,75.0,67.0,-8.0,12:38,16.0,0.0,0.0,0.0,0.0,0.0
8,9E,2023-01-05,5190.0,N183GJ,JFK,22:41,22:21,91.0,78.0,-20.0,...,91.0,78.0,-7.0,21:34,31.0,0.0,0.0,0.0,0.0,0.0
9,9E,2022-01-06,5446.0,N906XJ,JFK,13:45,13:28,75.0,63.0,-17.0,...,75.0,63.0,-5.0,12:38,13.0,0.0,0.0,0.0,0.0,0.0
10,9E,2023-01-06,5190.0,N195PQ,JFK,22:41,22:21,91.0,76.0,-20.0,...,91.0,76.0,-5.0,21:28,23.0,0.0,0.0,0.0,0.0,0.0
11,9E,2022-01-07,5446.0,N182GJ,JFK,13:45,15:00,75.0,65.0,75.0,...,75.0,65.0,85.0,14:05,10.0,0.0,22.0,0.0,0.0,53.0
12,9E,2023-01-07,5190.0,N301PQ,JFK,22:41,22:19,91.0,72.0,-22.0,...,91.0,72.0,-3.0,21:24,17.0,0.0,0.0,0.0,0.0,0.0
13,9E,2022-01-08,5446.0,N166PQ,JFK,13:45,13:28,75.0,66.0,-17.0,...,75.0,66.0,-8.0,12:35,13.0,0.0,0.0,0.0,0.0,0.0
14,9E,2023-01-08,5090.0,N300PQ,JFK,23:58,23:25,88.0,63.0,-33.0,...,88.0,63.0,-8.0,22:40,18.0,0.0,0.0,0.0,0.0,0.0
15,9E,2023-01-08,5114.0,N335PQ,JFK,17:48,17:39,88.0,64.0,-9.0,...,88.0,64.0,15.0,16:52,17.0,0.0,0.0,0.0,0.0,0.0
16,9E,2023-01-08,5202.0,N304PQ,JFK,11:14,10:53,84.0,64.0,-21.0,...,84.0,64.0,-1.0,10:03,14.0,0.0,0.0,0.0,0.0,0.0
17,9E,2022-01-09,5446.0,N153PQ,JFK,13:45,13:50,75.0,81.0,5.0,...,75.0,81.0,-1.0,12:58,29.0,0.0,0.0,0.0,0.0,0.0
18,9E,2023-01-09,5009.0,N131EV,JFK,23:54,23:36,84.0,71.0,-18.0,...,84.0,71.0,-5.0,22:46,21.0,0.0,0.0,0.0,0.0,0.0
19,9E,2023-01-09,5224.0,N936XJ,JFK,17:55,18:22,85.0,83.0,27.0,...,85.0,83.0,29.0,17:33,34.0,26.0,0.0,0.0,0.0,1.0

In [23]:
merged_data.columns

Index(['Carrier Code', 'Date (MM/DD/YYYY)', 'Flight Number', 'Tail Number',
       'Origin Airport', 'Scheduled Arrival Time', 'Actual Arrival Time',
       'Scheduled Elapsed Time (Minutes)', 'Actual Elapsed Time (Minutes)',
       'Arrival Delay (Minutes)', 'Wheels-on Time', 'Taxi-In time (Minutes)',
       'Delay Carrier (Minutes)_x', 'Delay Weather (Minutes)_x',
       'Delay National Aviation System (Minutes)_x',
       'Delay Security (Minutes)_x', 'Delay Late Aircraft Arrival (Minutes)_x',
       'Destination Airport', 'Scheduled departure time',
       'Actual departure time', 'Scheduled elapsed time (Minutes)',
       'Actual elapsed time (Minutes)', 'Departure delay (Minutes)',
       'Wheels-off time', 'Taxi-Out time (Minutes)',
       'Delay Carrier (Minutes)_y', 'Delay Weather (Minutes)_y',
       'Delay National Aviation System (Minutes)_y',
       'Delay Security (Minutes)_y',
       'Delay Late Aircraft Arrival (Minutes)_y'],
      dtype='object')

In [24]:
# merged_data.to_csv("filtered_data.csv", index=False)

In [25]:
len(merged_data.columns)

30

In [26]:
syr_weather_data = pd.read_csv("SYR_weather_data_sub_hourly.csv")
syr_weather_data['Location'] = 'SYR'
syr_weather_data.head()

/var/folders/kv/s4mg_r2n60q37wmj416xrvl40000gn/T/ipykernel_71520/1407464601.py:1: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  syr_weather_data = pd.read_csv("SYR_weather_data_sub_hourly.csv")

,app_temp,azimuth,clouds,dewpt,dhi,dni,elev_angle,ghi,pod,precip_rate,...,ts,uv,vis,weather.icon,weather.description,weather.code,wind_dir,wind_gust_spd,wind_spd,Location
0,3.6,334.9,42,-4.0,0,0,-36.0,0,n,0.0,...,1712547900,0.0,16,803,c03n,Broken clouds,0,1.0,1.00,SYR
1,5.8,330.7,42,-2.1,0,0,-34.7,0,n,0.0,...,1712547000,0.0,16,803,c03n,Broken clouds,0,1.0,1.00,SYR
2,5.0,326.5,42,-4.2,0,0,-33.3,0,n,0.0,...,1712546100,0.0,16,803,c03n,Broken clouds,210,1.6,1.54,SYR
3,6.9,322.3,42,-2.2,0,0,-32.0,0,n,0.0,...,1712545200,0.0,16,803,c03n,Broken clouds,0,1.0,1.00,SYR
4,6.2,318.7,0,-1.2,0,0,-30.1,0,n,0.0,...,1712544300,0.0,16,800,c01n,Clear Sky,20,1.6,1.54,SYR

In [27]:
syr_weather_data_des = syr_weather_data.add_suffix('_des')

In [28]:
syr_weather_data_des.head()

,app_temp_des,azimuth_des,clouds_des,dewpt_des,dhi_des,dni_des,elev_angle_des,ghi_des,pod_des,precip_rate_des,...,ts_des,uv_des,vis_des,weather.icon_des,weather.description_des,weather.code_des,wind_dir_des,wind_gust_spd_des,wind_spd_des,Location_des
0,3.6,334.9,42,-4.0,0,0,-36.0,0,n,0.0,...,1712547900,0.0,16,803,c03n,Broken clouds,0,1.0,1.00,SYR
1,5.8,330.7,42,-2.1,0,0,-34.7,0,n,0.0,...,1712547000,0.0,16,803,c03n,Broken clouds,0,1.0,1.00,SYR
2,5.0,326.5,42,-4.2,0,0,-33.3,0,n,0.0,...,1712546100,0.0,16,803,c03n,Broken clouds,210,1.6,1.54,SYR
3,6.9,322.3,42,-2.2,0,0,-32.0,0,n,0.0,...,1712545200,0.0,16,803,c03n,Broken clouds,0,1.0,1.00,SYR
4,6.2,318.7,0,-1.2,0,0,-30.1,0,n,0.0,...,1712544300,0.0,16,800,c01n,Clear Sky,20,1.6,1.54,SYR

In [29]:
# Convert 'timestamp_local' and 'timestamp_utc' to datetime
syr_weather_data_des['timestamp_local_des'] = pd.to_datetime(syr_weather_data_des['timestamp_local_des'])
syr_weather_data_des['timestamp_utc_des'] = pd.to_datetime(syr_weather_data_des['timestamp_utc_des'])

# Print the DataFrame to verify the changes
syr_weather_data_des.head()

,app_temp_des,azimuth_des,clouds_des,dewpt_des,dhi_des,dni_des,elev_angle_des,ghi_des,pod_des,precip_rate_des,...,ts_des,uv_des,vis_des,weather.icon_des,weather.description_des,weather.code_des,wind_dir_des,wind_gust_spd_des,wind_spd_des,Location_des
0,3.6,334.9,42,-4.0,0,0,-36.0,0,n,0.0,...,1712547900,0.0,16,803,c03n,Broken clouds,0,1.0,1.00,SYR
1,5.8,330.7,42,-2.1,0,0,-34.7,0,n,0.0,...,1712547000,0.0,16,803,c03n,Broken clouds,0,1.0,1.00,SYR
2,5.0,326.5,42,-4.2,0,0,-33.3,0,n,0.0,...,1712546100,0.0,16,803,c03n,Broken clouds,210,1.6,1.54,SYR
3,6.9,322.3,42,-2.2,0,0,-32.0,0,n,0.0,...,1712545200,0.0,16,803,c03n,Broken clouds,0,1.0,1.00,SYR
4,6.2,318.7,0,-1.2,0,0,-30.1,0,n,0.0,...,1712544300,0.0,16,800,c01n,Clear Sky,20,1.6,1.54,SYR

In [30]:
syr_weather_data_des.dtypes

app_temp_des                      float64
azimuth_des                       float64
clouds_des                          int64
dewpt_des                         float64
dhi_des                             int64
dni_des                             int64
elev_angle_des                    float64
ghi_des                             int64
pod_des                            object
precip_rate_des                   float64
pres_des                            int64
revision_status_des                object
rh_des                              int64
slp_des                             int64
snow_rate_des                     float64
solar_rad_des                       int64
temp_des                          float64
timestamp_local_des        datetime64[ns]
timestamp_utc_des          datetime64[ns]
ts_des                              int64
uv_des                            float64
vis_des                             int64
weather.icon_des                   object
weather.description_des            object
weather.code_des                   object
wind_dir_des                        int64
wind_gust_spd_des                 float64
wind_spd_des                      float64
Location_des                       object
dtype: object

In [31]:
merged_data.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),...,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes)_y,Delay Weather (Minutes)_y,Delay National Aviation System (Minutes)_y,Delay Security (Minutes)_y,Delay Late Aircraft Arrival (Minutes)_y
0,9E,2023-01-01,5190.0,N325PQ,JFK,22:41,22:13,91.0,68.0,-28.0,...,91.0,68.0,-5.0,21:23,18.0,0.0,0.0,0.0,0.0,0.0
1,9E,2022-01-02,5531.0,N678CA,JFK,14:12,17:12,77.0,84.0,180.0,...,77.0,84.0,173.0,16:08,20.0,173.0,0.0,7.0,0.0,0.0
2,9E,2023-01-02,5190.0,N195PQ,JFK,22:41,22:46,91.0,77.0,5.0,...,91.0,77.0,19.0,21:54,25.0,0.0,0.0,0.0,0.0,0.0
3,9E,2022-01-03,5531.0,N602LR,JFK,14:12,14:24,77.0,81.0,12.0,...,77.0,81.0,8.0,13:34,31.0,0.0,0.0,0.0,0.0,0.0
4,9E,2023-01-03,5190.0,N303PQ,JFK,22:41,22:23,91.0,78.0,-18.0,...,91.0,78.0,-5.0,21:35,30.0,0.0,0.0,0.0,0.0,0.0

In [32]:
merged_data.dtypes

Carrier Code                                          object
Date (MM/DD/YYYY)                             datetime64[ns]
Flight Number                                        float64
Tail Number                                           object
Origin Airport                                        object
Scheduled Arrival Time                                object
Actual Arrival Time                                   object
Scheduled Elapsed Time (Minutes)                     float64
Actual Elapsed Time (Minutes)                        float64
Arrival Delay (Minutes)                              float64
Wheels-on Time                                        object
Taxi-In time (Minutes)                               float64
Delay Carrier (Minutes)_x                            float64
Delay Weather (Minutes)_x                            float64
Delay National Aviation System (Minutes)_x           float64
Delay Security (Minutes)_x                           float64
Delay Late Aircraft Arrival (Minutes)_x              float64
Destination Airport                                   object
Scheduled departure time                              object
Actual departure time                                 object
Scheduled elapsed time (Minutes)                     float64
Actual elapsed time (Minutes)                        float64
Departure delay (Minutes)                            float64
Wheels-off time                                       object
Taxi-Out time (Minutes)                              float64
Delay Carrier (Minutes)_y                            float64
Delay Weather (Minutes)_y                            float64
Delay National Aviation System (Minutes)_y           float64
Delay Security (Minutes)_y                           float64
Delay Late Aircraft Arrival (Minutes)_y              float64
dtype: object

In [33]:
merged_data.columns

Index(['Carrier Code', 'Date (MM/DD/YYYY)', 'Flight Number', 'Tail Number',
       'Origin Airport', 'Scheduled Arrival Time', 'Actual Arrival Time',
       'Scheduled Elapsed Time (Minutes)', 'Actual Elapsed Time (Minutes)',
       'Arrival Delay (Minutes)', 'Wheels-on Time', 'Taxi-In time (Minutes)',
       'Delay Carrier (Minutes)_x', 'Delay Weather (Minutes)_x',
       'Delay National Aviation System (Minutes)_x',
       'Delay Security (Minutes)_x', 'Delay Late Aircraft Arrival (Minutes)_x',
       'Destination Airport', 'Scheduled departure time',
       'Actual departure time', 'Scheduled elapsed time (Minutes)',
       'Actual elapsed time (Minutes)', 'Departure delay (Minutes)',
       'Wheels-off time', 'Taxi-Out time (Minutes)',
       'Delay Carrier (Minutes)_y', 'Delay Weather (Minutes)_y',
       'Delay National Aviation System (Minutes)_y',
       'Delay Security (Minutes)_y',
       'Delay Late Aircraft Arrival (Minutes)_y'],
      dtype='object')

In [34]:
# merged_data = merged_data.drop(['Actual Arrival Time', 'Actual Elapsed Time (Minutes)', 'Arrival Delay (Minutes)', 'Wheels-on Time', 'Taxi-In time (Minutes)',
#        'Delay Carrier (Minutes)_x', 'Delay Weather (Minutes)_x',
#        'Delay National Aviation System (Minutes)_x',
#        'Delay Security (Minutes)_x', 'Delay Late Aircraft Arrival (Minutes)_x', 'Actual departure time', 'Actual elapsed time (Minutes)', 'Departure delay (Minutes)',
#        'Wheels-off time', 'Taxi-Out time (Minutes)',
#        'Delay Carrier (Minutes)_y', 'Delay Weather (Minutes)_y',
#        'Delay National Aviation System (Minutes)_y',
#        'Delay Security (Minutes)_y',
#        'Delay Late Aircraft Arrival (Minutes)_y'], axis=1)
# merged_data.head()

In [35]:
merged_data.columns

Index(['Carrier Code', 'Date (MM/DD/YYYY)', 'Flight Number', 'Tail Number',
       'Origin Airport', 'Scheduled Arrival Time', 'Actual Arrival Time',
       'Scheduled Elapsed Time (Minutes)', 'Actual Elapsed Time (Minutes)',
       'Arrival Delay (Minutes)', 'Wheels-on Time', 'Taxi-In time (Minutes)',
       'Delay Carrier (Minutes)_x', 'Delay Weather (Minutes)_x',
       'Delay National Aviation System (Minutes)_x',
       'Delay Security (Minutes)_x', 'Delay Late Aircraft Arrival (Minutes)_x',
       'Destination Airport', 'Scheduled departure time',
       'Actual departure time', 'Scheduled elapsed time (Minutes)',
       'Actual elapsed time (Minutes)', 'Departure delay (Minutes)',
       'Wheels-off time', 'Taxi-Out time (Minutes)',
       'Delay Carrier (Minutes)_y', 'Delay Weather (Minutes)_y',
       'Delay National Aviation System (Minutes)_y',
       'Delay Security (Minutes)_y',
       'Delay Late Aircraft Arrival (Minutes)_y'],
      dtype='object')

In [36]:

merged_data.dtypes

Carrier Code                                          object
Date (MM/DD/YYYY)                             datetime64[ns]
Flight Number                                        float64
Tail Number                                           object
Origin Airport                                        object
Scheduled Arrival Time                                object
Actual Arrival Time                                   object
Scheduled Elapsed Time (Minutes)                     float64
Actual Elapsed Time (Minutes)                        float64
Arrival Delay (Minutes)                              float64
Wheels-on Time                                        object
Taxi-In time (Minutes)                               float64
Delay Carrier (Minutes)_x                            float64
Delay Weather (Minutes)_x                            float64
Delay National Aviation System (Minutes)_x           float64
Delay Security (Minutes)_x                           float64
Delay Late Aircraft Arrival (Minutes)_x              float64
Destination Airport                                   object
Scheduled departure time                              object
Actual departure time                                 object
Scheduled elapsed time (Minutes)                     float64
Actual elapsed time (Minutes)                        float64
Departure delay (Minutes)                            float64
Wheels-off time                                       object
Taxi-Out time (Minutes)                              float64
Delay Carrier (Minutes)_y                            float64
Delay Weather (Minutes)_y                            float64
Delay National Aviation System (Minutes)_y           float64
Delay Security (Minutes)_y                           float64
Delay Late Aircraft Arrival (Minutes)_y              float64
dtype: object

In [37]:
# Convert 'Scheduled Arrival Time' to '%H:%M:%S' format
merged_data['Scheduled Arrival Time'] = pd.to_datetime(merged_data['Scheduled Arrival Time']).dt.strftime('%H:%M:%S')
merged_data['Scheduled departure time'] = pd.to_datetime(merged_data['Scheduled departure time']).dt.strftime('%H:%M:%S')

# Combine 'Date (MM/DD/YYYY)' and 'Scheduled Arrival Time' into a single datetime column
merged_data['Arrival_time'] = pd.to_datetime(merged_data['Date (MM/DD/YYYY)'].astype(str) + ' ' + merged_data['Scheduled Arrival Time'].astype(str))
merged_data['departure_time'] = pd.to_datetime(merged_data['Date (MM/DD/YYYY)'].astype(str) + ' ' + merged_data['Scheduled departure time'].astype(str))
merged_data.head()

/var/folders/kv/s4mg_r2n60q37wmj416xrvl40000gn/T/ipykernel_71520/3605360661.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  merged_data['Scheduled Arrival Time'] = pd.to_datetime(merged_data['Scheduled Arrival Time']).dt.strftime('%H:%M:%S')
/var/folders/kv/s4mg_r2n60q37wmj416xrvl40000gn/T/ipykernel_71520/3605360661.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  merged_data['Scheduled departure time'] = pd.to_datetime(merged_data['Scheduled departure time']).dt.strftime('%H:%M:%S')

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),...,Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes)_y,Delay Weather (Minutes)_y,Delay National Aviation System (Minutes)_y,Delay Security (Minutes)_y,Delay Late Aircraft Arrival (Minutes)_y,Arrival_time,departure_time
0,9E,2023-01-01,5190.0,N325PQ,JFK,22:41:00,22:13,91.0,68.0,-28.0,...,-5.0,21:23,18.0,0.0,0.0,0.0,0.0,0.0,2023-01-01 22:41:00,2023-01-01 21:10:00
1,9E,2022-01-02,5531.0,N678CA,JFK,14:12:00,17:12,77.0,84.0,180.0,...,173.0,16:08,20.0,173.0,0.0,7.0,0.0,0.0,2022-01-02 14:12:00,2022-01-02 12:55:00
2,9E,2023-01-02,5190.0,N195PQ,JFK,22:41:00,22:46,91.0,77.0,5.0,...,19.0,21:54,25.0,0.0,0.0,0.0,0.0,0.0,2023-01-02 22:41:00,2023-01-02 21:10:00
3,9E,2022-01-03,5531.0,N602LR,JFK,14:12:00,14:24,77.0,81.0,12.0,...,8.0,13:34,31.0,0.0,0.0,0.0,0.0,0.0,2022-01-03 14:12:00,2022-01-03 12:55:00
4,9E,2023-01-03,5190.0,N303PQ,JFK,22:41:00,22:23,91.0,78.0,-18.0,...,-5.0,21:35,30.0,0.0,0.0,0.0,0.0,0.0,2023-01-03 22:41:00,2023-01-03 21:10:00

In [38]:
ord_weather_data = pd.read_csv("ORD_weather_data_sub_hourly.csv")
ord_weather_data['Location'] = 'ORD'
ord_weather_data.head()

/var/folders/kv/s4mg_r2n60q37wmj416xrvl40000gn/T/ipykernel_71520/4074338693.py:1: DtypeWarning: Columns (22) have mixed types. Specify dtype option on import or set low_memory=False.
  ord_weather_data = pd.read_csv("ORD_weather_data_sub_hourly.csv")

,app_temp,azimuth,clouds,dewpt,dhi,dni,elev_angle,ghi,pod,precip_rate,...,ts,uv,vis,weather.code,weather.icon,weather.description,wind_dir,wind_gust_spd,wind_spd,Location
0,-8.9,3.6,25,-6.3,0,0,-71.0,0,n,0.0,...,1577858400,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
1,-9.0,12.9,25,-6.4,0,0,-69.9,0,n,0.0,...,1577859300,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
2,-9.2,22.1,25,-6.6,0,0,-68.9,0,n,0.0,...,1577860200,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
3,-9.4,31.4,25,-6.8,0,0,-67.8,0,n,0.0,...,1577861100,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
4,-9.3,40.6,25,-6.8,0,0,-66.7,0,n,0.0,...,1577862000,0.0,16,802,c02n,Scattered clouds,270,6.4,3.35,ORD

In [39]:
jfk_weather_data = pd.read_csv("JFK_weather_data_sub_hourly.csv")
jfk_weather_data['Location'] = 'JFK'
jfk_weather_data.head()

/var/folders/kv/s4mg_r2n60q37wmj416xrvl40000gn/T/ipykernel_71520/177976352.py:1: DtypeWarning: Columns (23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  jfk_weather_data = pd.read_csv("JFK_weather_data_sub_hourly.csv")

,app_temp,azimuth,clouds,dewpt,dhi,dni,elev_angle,ghi,pod,precip_rate,...,ts,uv,vis,weather.icon,weather.description,weather.code,wind_dir,wind_gust_spd,wind_spd,Location
0,1.1,1.4,100,-0.8,0,0,-72.4,0,n,0.0,...,1577854800,0.0,16,c04n,Overcast clouds,804,275,11.2,7.07,JFK
1,0.7,11.3,100,-1.6,0,0,-71.3,0,n,0.0,...,1577855700,0.0,16,c04n,Overcast clouds,804,275,11.6,7.44,JFK
2,0.4,21.2,100,-2.2,0,0,-70.3,0,n,0.0,...,1577856600,0.0,16,c04n,Overcast clouds,804,280,12.0,7.82,JFK
3,0.1,31.2,100,-2.8,0,0,-69.2,0,n,0.0,...,1577857500,0.0,16,c04n,Overcast clouds,804,280,12.4,8.19,JFK
4,0.1,41.1,100,-2.8,0,0,-68.1,0,n,0.0,...,1577858400,0.0,16,c04n,Overcast clouds,804,280,12.0,8.19,JFK

In [40]:
mco_weather_data = pd.read_csv("MCO_weather_data_sub_hourly.csv")
mco_weather_data['Location'] = 'MCO'
mco_weather_data.head()

,app_temp,azimuth,clouds,dewpt,dhi,dni,elev_angle,ghi,pod,precip_rate,...,ts,uv,vis,weather.description,weather.code,weather.icon,wind_dir,wind_gust_spd,wind_spd,Location
0,13.3,308.5,0,7.1,0,0,-81.6,0,n,0.0,...,1577854800,0.0,16,Clear Sky,800,c01n,260,3.2,2.10,MCO
1,13.2,245.0,6,7.2,0,0,-81.5,0,n,0.0,...,1577855700,0.0,16,Few clouds,801,c02n,265,3.2,2.22,MCO
2,13.1,181.5,12,7.5,0,0,-81.4,0,n,0.0,...,1577856600,0.0,16,Few clouds,801,c02n,270,3.2,2.35,MCO
3,12.9,118.0,18,7.6,0,0,-81.2,0,n,0.0,...,1577857500,0.0,16,Few clouds,801,c02n,275,3.2,2.47,MCO
4,12.8,54.5,25,7.7,0,0,-81.1,0,n,0.0,...,1577858400,0.0,16,Scattered clouds,802,c02n,280,3.2,2.60,MCO

In [41]:
weather_data = pd.concat([ord_weather_data, jfk_weather_data, mco_weather_data], ignore_index=True)
weather_data.head()

,app_temp,azimuth,clouds,dewpt,dhi,dni,elev_angle,ghi,pod,precip_rate,...,ts,uv,vis,weather.code,weather.icon,weather.description,wind_dir,wind_gust_spd,wind_spd,Location
0,-8.9,3.6,25,-6.3,0,0,-71.0,0,n,0.0,...,1577858400,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
1,-9.0,12.9,25,-6.4,0,0,-69.9,0,n,0.0,...,1577859300,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
2,-9.2,22.1,25,-6.6,0,0,-68.9,0,n,0.0,...,1577860200,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
3,-9.4,31.4,25,-6.8,0,0,-67.8,0,n,0.0,...,1577861100,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
4,-9.3,40.6,25,-6.8,0,0,-66.7,0,n,0.0,...,1577862000,0.0,16,802,c02n,Scattered clouds,270,6.4,3.35,ORD

In [42]:
# Convert 'timestamp_local' and 'timestamp_utc' to datetime
weather_data['timestamp_local'] = pd.to_datetime(weather_data['timestamp_local'])
weather_data['timestamp_utc'] = pd.to_datetime(weather_data['timestamp_utc'])

# Print the DataFrame to verify the changes
weather_data.head()

,app_temp,azimuth,clouds,dewpt,dhi,dni,elev_angle,ghi,pod,precip_rate,...,ts,uv,vis,weather.code,weather.icon,weather.description,wind_dir,wind_gust_spd,wind_spd,Location
0,-8.9,3.6,25,-6.3,0,0,-71.0,0,n,0.0,...,1577858400,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
1,-9.0,12.9,25,-6.4,0,0,-69.9,0,n,0.0,...,1577859300,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
2,-9.2,22.1,25,-6.6,0,0,-68.9,0,n,0.0,...,1577860200,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
3,-9.4,31.4,25,-6.8,0,0,-67.8,0,n,0.0,...,1577861100,0.0,16,802,c02n,Scattered clouds,270,6.4,3.60,ORD
4,-9.3,40.6,25,-6.8,0,0,-66.7,0,n,0.0,...,1577862000,0.0,16,802,c02n,Scattered clouds,270,6.4,3.35,ORD

In [43]:
weather_data.dtypes

app_temp                      float64
azimuth                       float64
clouds                          int64
dewpt                         float64
dhi                             int64
dni                             int64
elev_angle                    float64
ghi                             int64
pod                            object
precip_rate                   float64
pres                            int64
revision_status                object
rh                              int64
slp                             int64
snow_rate                     float64
solar_rad                       int64
temp                          float64
timestamp_local        datetime64[ns]
timestamp_utc          datetime64[ns]
ts                              int64
uv                            float64
vis                             int64
weather.code                   object
weather.icon                   object
weather.description            object
wind_dir                        int64
wind_gust_spd                 float64
wind_spd                      float64
Location                       object
dtype: object

In [44]:
weather_data['timestamp_local']

0        2020-01-01 00:00:00
1        2020-01-01 00:15:00
2        2020-01-01 00:30:00
3        2020-01-01 00:45:00
4        2020-01-01 01:00:00
                 ...
448975   2024-04-07 22:45:00
448976   2024-04-07 23:00:00
448977   2024-04-07 23:15:00
448978   2024-04-07 23:30:00
448979   2024-04-07 23:45:00
Name: timestamp_local, Length: 448980, dtype: datetime64[ns]

In [45]:
merged_data['Arrival_time'] = merged_data['Arrival_time'].dt.round('15min')
merged_data.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),...,Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes)_y,Delay Weather (Minutes)_y,Delay National Aviation System (Minutes)_y,Delay Security (Minutes)_y,Delay Late Aircraft Arrival (Minutes)_y,Arrival_time,departure_time
0,9E,2023-01-01,5190.0,N325PQ,JFK,22:41:00,22:13,91.0,68.0,-28.0,...,-5.0,21:23,18.0,0.0,0.0,0.0,0.0,0.0,2023-01-01 22:45:00,2023-01-01 21:10:00
1,9E,2022-01-02,5531.0,N678CA,JFK,14:12:00,17:12,77.0,84.0,180.0,...,173.0,16:08,20.0,173.0,0.0,7.0,0.0,0.0,2022-01-02 14:15:00,2022-01-02 12:55:00
2,9E,2023-01-02,5190.0,N195PQ,JFK,22:41:00,22:46,91.0,77.0,5.0,...,19.0,21:54,25.0,0.0,0.0,0.0,0.0,0.0,2023-01-02 22:45:00,2023-01-02 21:10:00
3,9E,2022-01-03,5531.0,N602LR,JFK,14:12:00,14:24,77.0,81.0,12.0,...,8.0,13:34,31.0,0.0,0.0,0.0,0.0,0.0,2022-01-03 14:15:00,2022-01-03 12:55:00
4,9E,2023-01-03,5190.0,N303PQ,JFK,22:41:00,22:23,91.0,78.0,-18.0,...,-5.0,21:35,30.0,0.0,0.0,0.0,0.0,0.0,2023-01-03 22:45:00,2023-01-03 21:10:00

In [46]:
merged_data['departure_time'] = merged_data['departure_time'].dt.round('15min')
merged_data.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),...,Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes)_y,Delay Weather (Minutes)_y,Delay National Aviation System (Minutes)_y,Delay Security (Minutes)_y,Delay Late Aircraft Arrival (Minutes)_y,Arrival_time,departure_time
0,9E,2023-01-01,5190.0,N325PQ,JFK,22:41:00,22:13,91.0,68.0,-28.0,...,-5.0,21:23,18.0,0.0,0.0,0.0,0.0,0.0,2023-01-01 22:45:00,2023-01-01 21:15:00
1,9E,2022-01-02,5531.0,N678CA,JFK,14:12:00,17:12,77.0,84.0,180.0,...,173.0,16:08,20.0,173.0,0.0,7.0,0.0,0.0,2022-01-02 14:15:00,2022-01-02 13:00:00
2,9E,2023-01-02,5190.0,N195PQ,JFK,22:41:00,22:46,91.0,77.0,5.0,...,19.0,21:54,25.0,0.0,0.0,0.0,0.0,0.0,2023-01-02 22:45:00,2023-01-02 21:15:00
3,9E,2022-01-03,5531.0,N602LR,JFK,14:12:00,14:24,77.0,81.0,12.0,...,8.0,13:34,31.0,0.0,0.0,0.0,0.0,0.0,2022-01-03 14:15:00,2022-01-03 13:00:00
4,9E,2023-01-03,5190.0,N303PQ,JFK,22:41:00,22:23,91.0,78.0,-18.0,...,-5.0,21:35,30.0,0.0,0.0,0.0,0.0,0.0,2023-01-03 22:45:00,2023-01-03 21:15:00

In [47]:
merged_data['departure_time']

0      2023-01-01 21:15:00
1      2022-01-02 13:00:00
2      2023-01-02 21:15:00
3      2022-01-03 13:00:00
4      2023-01-03 21:15:00
               ...
5618   2023-12-29 18:15:00
5619   2022-12-30 18:15:00
5620   2023-12-30 21:00:00
5621   2022-12-31 18:15:00
5622   2023-12-31 18:15:00
Name: departure_time, Length: 5623, dtype: datetime64[ns]

In [48]:
# Convert 'departure_time' to timezone-naive datetime (local time)
merged_data['departure_time'] = merged_data['departure_time'].dt.tz_localize(None)
merged_data['Arrival_time'] = merged_data['Arrival_time'].dt.tz_localize(None)

In [49]:

merged_data = pd.merge(merged_data, weather_data, 
                       left_on=['departure_time', 'Origin Airport'], 
                       right_on=['timestamp_local', 'Location'],
                       how='left')
merged_data.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),...,ts,uv,vis,weather.code,weather.icon,weather.description,wind_dir,wind_gust_spd,wind_spd,Location
0,9E,2023-01-01,5190.0,N325PQ,JFK,22:41:00,22:13,91.0,68.0,-28.0,...,1672625700,0.0,16,Broken clouds,803,c03n,245,4.9,4.09,JFK
1,9E,2022-01-02,5531.0,N678CA,JFK,14:12:00,17:12,77.0,84.0,180.0,...,1641146400,0.7,16,804,c04d,Overcast clouds,240,7.6,4.59,JFK
2,9E,2023-01-02,5190.0,N195PQ,JFK,22:41:00,22:46,91.0,77.0,5.0,...,1672712100,0.0,16,Light rain,500,r01n,190,4.3,2.60,JFK
3,9E,2022-01-03,5531.0,N602LR,JFK,14:12:00,14:24,77.0,81.0,12.0,...,1641232800,0.7,16,600,s01d,Light snow,20,11.3,6.70,JFK
4,9E,2023-01-03,5190.0,N303PQ,JFK,22:41:00,22:23,91.0,78.0,-18.0,...,1672798500,0.0,2,Fog,741,a05n,175,9.2,2.35,JFK

In [50]:
merged_data.iloc[0]

Carrier Code                            9E
Date (MM/DD/YYYY)      2023-01-01 00:00:00
Flight Number                       5190.0
Tail Number                         N325PQ
Origin Airport                         JFK
                              ...
weather.description                   c03n
wind_dir                               245
wind_gust_spd                          4.9
wind_spd                              4.09
Location                               JFK
Name: 0, Length: 61, dtype: object

In [51]:
merged_data = pd.merge(merged_data, syr_weather_data_des, 
                       left_on=['Arrival_time', 'Destination Airport'], 
                       right_on=['timestamp_local_des', 'Location_des'], 
                       how='left')
merged_data.head()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),...,ts_des,uv_des,vis_des,weather.icon_des,weather.description_des,weather.code_des,wind_dir_des,wind_gust_spd_des,wind_spd_des,Location_des
0,9E,2023-01-01,5190.0,N325PQ,JFK,22:41:00,22:13,91.0,68.0,-28.0,...,1672631100,0.0,11,804,c04n,Overcast clouds,285,3.4,1.50,SYR
1,9E,2022-01-02,5531.0,N678CA,JFK,14:12:00,17:12,77.0,84.0,180.0,...,1641150900,0.5,12,c04d,Overcast clouds,804,305,10.9,4.97,SYR
2,9E,2023-01-02,5190.0,N195PQ,JFK,22:41:00,22:46,91.0,77.0,5.0,...,1672717500,0.0,16,804,c04n,Overcast clouds,75,2.4,0.50,SYR
3,9E,2022-01-03,5531.0,N602LR,JFK,14:12:00,14:24,77.0,81.0,12.0,...,1641237300,1.1,16,c03d,Broken clouds,803,320,8.4,2.60,SYR
4,9E,2023-01-03,5190.0,N303PQ,JFK,22:41:00,22:23,91.0,78.0,-18.0,...,1672803900,0.0,4,804,c04n,Overcast clouds,70,4.0,2.10,SYR

In [52]:
merged_data.to_csv("airline_dataset_2022_23.csv", index=False)

In [53]:
merged_data.columns

Index(['Carrier Code', 'Date (MM/DD/YYYY)', 'Flight Number', 'Tail Number',
       'Origin Airport', 'Scheduled Arrival Time', 'Actual Arrival Time',
       'Scheduled Elapsed Time (Minutes)', 'Actual Elapsed Time (Minutes)',
       'Arrival Delay (Minutes)', 'Wheels-on Time', 'Taxi-In time (Minutes)',
       'Delay Carrier (Minutes)_x', 'Delay Weather (Minutes)_x',
       'Delay National Aviation System (Minutes)_x',
       'Delay Security (Minutes)_x', 'Delay Late Aircraft Arrival (Minutes)_x',
       'Destination Airport', 'Scheduled departure time',
       'Actual departure time', 'Scheduled elapsed time (Minutes)',
       'Actual elapsed time (Minutes)', 'Departure delay (Minutes)',
       'Wheels-off time', 'Taxi-Out time (Minutes)',
       'Delay Carrier (Minutes)_y', 'Delay Weather (Minutes)_y',
       'Delay National Aviation System (Minutes)_y',
       'Delay Security (Minutes)_y', 'Delay Late Aircraft Arrival (Minutes)_y',
       'Arrival_time', 'departure_time', 'app_temp', 'azimuth', 'clouds',
       'dewpt', 'dhi', 'dni', 'elev_angle', 'ghi', 'pod', 'precip_rate',
       'pres', 'revision_status', 'rh', 'slp', 'snow_rate', 'solar_rad',
       'temp', 'timestamp_local', 'timestamp_utc', 'ts', 'uv', 'vis',
       'weather.code', 'weather.icon', 'weather.description', 'wind_dir',
       'wind_gust_spd', 'wind_spd', 'Location', 'app_temp_des', 'azimuth_des',
       'clouds_des', 'dewpt_des', 'dhi_des', 'dni_des', 'elev_angle_des',
       'ghi_des', 'pod_des', 'precip_rate_des', 'pres_des',
       'revision_status_des', 'rh_des', 'slp_des', 'snow_rate_des',
       'solar_rad_des', 'temp_des', 'timestamp_local_des', 'timestamp_utc_des',
       'ts_des', 'uv_des', 'vis_des', 'weather.icon_des',
       'weather.description_des', 'weather.code_des', 'wind_dir_des',
       'wind_gust_spd_des', 'wind_spd_des', 'Location_des'],
      dtype='object')

In [54]:
len(merged_data)

5623

In [55]:
datetime_columns = merged_data.select_dtypes(include=['datetime64']).columns

# Create a new DataFrame to store datetime values
datetime_data = merged_data[datetime_columns].copy()
datetime_data.head()

,Date (MM/DD/YYYY),Arrival_time,departure_time,timestamp_local,timestamp_utc,timestamp_local_des,timestamp_utc_des
0,2023-01-01,2023-01-01 22:45:00,2023-01-01 21:15:00,2023-01-01 21:15:00,2023-01-02 02:15:00,2023-01-01 22:45:00,2023-01-02 03:45:00
1,2022-01-02,2022-01-02 14:15:00,2022-01-02 13:00:00,2022-01-02 13:00:00,2022-01-02 18:00:00,2022-01-02 14:15:00,2022-01-02 19:15:00
2,2023-01-02,2023-01-02 22:45:00,2023-01-02 21:15:00,2023-01-02 21:15:00,2023-01-03 02:15:00,2023-01-02 22:45:00,2023-01-03 03:45:00
3,2022-01-03,2022-01-03 14:15:00,2022-01-03 13:00:00,2022-01-03 13:00:00,2022-01-03 18:00:00,2022-01-03 14:15:00,2022-01-03 19:15:00
4,2023-01-03,2023-01-03 22:45:00,2023-01-03 21:15:00,2023-01-03 21:15:00,2023-01-04 02:15:00,2023-01-03 22:45:00,2023-01-04 03:45:00

In [56]:
weather_data.to_csv('weather_data.csv')